report_comment: >
    This is a test
report_section_order:
  software_versions:
    order: -1000
  hifi2genome-summary:
    order: -1000

export_plots: true

data_format: "yaml"

top_modules:
  - "busco"
  - "quast"
